name: betto_pdf_widgets
description:
  A Flutter package wrapping the PDFium library for PDF rendering, text
  extraction, and annotation support.
version: 0.1.0-dev.1
repository: https://github.com/bettongia/pdf_widgets
issue_tracker: https://github.com/bettongia/pdf_widgets/issues
homepage: https://bettongia.github.io/pdf_widgets

topics:
  - pdfium
  - pdf
  - ffi

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  betto_pdfium: ^0.1.0-dev.2

  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.7.0

flutter:
  uses-material-design: true
  generate: true
