// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Mocks generated by Mockito 5.4.6 from annotations
// in betto_pdf/test/pdf_page_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:betto_pdf_widgets/betto_pdf_widgets.dart' as _i4;
import 'package:betto_pdf_widgets/betto_pdf_widgets.dart' as _i2;
import 'package:betto_pdf_widgets/betto_pdf_widgets.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePdfMetadata_0 extends _i1.SmartFake implements _i2.PdfMetadata {
  _FakePdfMetadata_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePdfDocumentInfo_1 extends _i1.SmartFake
    implements _i2.PdfDocumentInfo {
  _FakePdfDocumentInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePdfPageSize_2 extends _i1.SmartFake implements _i3.PdfPageSize {
  _FakePdfPageSize_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PdfDocument].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfDocument extends _i1.Mock implements _i4.PdfDocument {
  MockPdfDocument() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> get pageCount =>
      (super.noSuchMethod(
            Invocation.getter(#pageCount),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i2.PdfMetadata> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i5.Future<_i2.PdfMetadata>.value(
              _FakePdfMetadata_0(this, Invocation.method(#getMetadata, [])),
            ),
          )
          as _i5.Future<_i2.PdfMetadata>);

  @override
  _i5.Future<_i2.PdfDocumentInfo> getDocumentInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentInfo, []),
            returnValue: _i5.Future<_i2.PdfDocumentInfo>.value(
              _FakePdfDocumentInfo_1(
                this,
                Invocation.method(#getDocumentInfo, []),
              ),
            ),
          )
          as _i5.Future<_i2.PdfDocumentInfo>);

  @override
  _i5.Stream<_i2.PdfPageText> extractPlainText({
    int? pageIndex,
    _i2.PdfTextExtractorConfig? config = const _i2.PdfTextExtractorConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extractPlainText, [], {
              #pageIndex: pageIndex,
              #config: config,
            }),
            returnValue: _i5.Stream<_i2.PdfPageText>.empty(),
          )
          as _i5.Stream<_i2.PdfPageText>);

  @override
  _i5.Stream<_i2.PdfPageAnnotations> extractAnnotations({int? pageIndex}) =>
      (super.noSuchMethod(
            Invocation.method(#extractAnnotations, [], {#pageIndex: pageIndex}),
            returnValue: _i5.Stream<_i2.PdfPageAnnotations>.empty(),
          )
          as _i5.Stream<_i2.PdfPageAnnotations>);

  @override
  _i5.Stream<_i2.PdfSearchMatch> search(
    String query, {
    Set<_i2.PdfSearchFlag> flags = const {},
    int? pageIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [query],
              {#flags: flags, #pageIndex: pageIndex},
            ),
            returnValue: _i5.Stream<_i2.PdfSearchMatch>.empty(),
          )
          as _i5.Stream<_i2.PdfSearchMatch>);

  @override
  _i5.Future<bool> isPlainTextExtractable({
    _i2.PdfTextExtractorConfig? config = const _i2.PdfTextExtractorConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isPlainTextExtractable, [], {#config: config}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.PdfPageSize> getPageSize(int? pageIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getPageSize, [pageIndex]),
            returnValue: _i5.Future<_i3.PdfPageSize>.value(
              _FakePdfPageSize_2(
                this,
                Invocation.method(#getPageSize, [pageIndex]),
              ),
            ),
          )
          as _i5.Future<_i3.PdfPageSize>);

  @override
  _i5.Future<({_i8.Uint8List pixels, int pixelWidth, int pixelHeight})>
  renderPageToBytes(
    int? pageIndex,
    int? pixelWidth,
    int? pixelHeight, {
    bool? renderAnnotations = true,
    bool? lcdText = false,
    int? backgroundColor = 0xFFFFFFFF,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #renderPageToBytes,
              [pageIndex, pixelWidth, pixelHeight],
              {
                #renderAnnotations: renderAnnotations,
                #lcdText: lcdText,
                #backgroundColor: backgroundColor,
              },
            ),
            returnValue:
                _i5.Future<
                  ({_i8.Uint8List pixels, int pixelWidth, int pixelHeight})
                >.value((
                  pixels: _i8.Uint8List(0),
                  pixelWidth: 0,
                  pixelHeight: 0,
                )),
          )
          as _i5.Future<
            ({_i8.Uint8List pixels, int pixelWidth, int pixelHeight})
          >);

  @override
  _i5.Future<_i2.PdfThumbnail?> getThumbnail(
    int pageIndex, {
    bool generateIfAbsent = true,
    int maxDimension = 256,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getThumbnail,
              [pageIndex],
              {
                #generateIfAbsent: generateIfAbsent,
                #maxDimension: maxDimension,
              },
            ),
            returnValue: _i5.Future<_i2.PdfThumbnail?>.value(null),
            returnValueForMissingStub: _i5.Future<_i2.PdfThumbnail?>.value(
              null,
            ),
          )
          as _i5.Future<_i2.PdfThumbnail?>);

  @override
  _i5.Future<List<_i2.PdfTocEntry>> get tableOfContents =>
      (super.noSuchMethod(
            Invocation.getter(#tableOfContents),
            returnValue: _i5.Future<List<_i2.PdfTocEntry>>.value([]),
            returnValueForMissingStub: _i5.Future<List<_i2.PdfTocEntry>>.value(
              [],
            ),
          )
          as _i5.Future<List<_i2.PdfTocEntry>>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
